apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-dotnet
  labels:
    app: aspnetapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetapp
  template:
    metadata:
      labels:
        app: aspnetapp
    spec:
      containers:
      - name: aspnetapp
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /diag
          name: diagvol        
        resources:
          requests:
            memory: "60Mi"
            cpu: "250m"
          limits:
            memory: "100Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 8080
      volumes:
      - name: diagvol
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hello-dotnet
  labels:
    hpecp.hpe.com/hpecp-internal-gateway: "true"  
spec:
  type: NodePort
  selector:
    app: aspnetapp
  ports:
    - port: 8080